services:
  user-org:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./app:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
    networks:
      - ams-network
    ports:
      - 7002:7002
    env_file:
      - .env

networks:
  ams-network:
    name: ams-network
    driver: bridge