services:
  auth:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./app:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
    networks:
      - ams-network
    ports:
      - 7001:7001
    env_file:
      - .env

networks:
  ams-network:
    name: ams-network
    driver: bridge